# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'verbose_name': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100, verbose_name='URI')),
            ],
            options={
                'verbose_name_plural': 'Músicas',
                'verbose_name': 'Música',
            },
        ),
        migrations.CreateModel(
            name='MusicaHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título')),
                ('classes', models.ManyToManyField(to='core.Classe')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_musica_set', to='core.Musica', verbose_name='Música')),
            ],
            options={
                'verbose_name_plural': 'Músicas',
                'verbose_name': 'Música',
            },
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes_set', to='core.Musica', verbose_name='Música')),
            ],
            options={
                'verbose_name_plural': 'Versões',
                'verbose_name': 'Versão',
            },
        ),
        migrations.CreateModel(
            name='VersaoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('descr', models.CharField(max_length=256, verbose_name='Descrição')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_versao_set', to='core.Versao', verbose_name='Versão')),
            ],
            options={
                'verbose_name_plural': 'Versões',
                'verbose_name': 'Versão',
            },
        ),
    ]
