# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['id'], 'permissions': (('list_classe', 'Visualização da Lista de classes'),), 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='musica',
            name='uri',
            field=models.CharField(max_length=100, unique=True, verbose_name='URI'),
        ),
    ]
